apiVersion: v1
kind: Secret

metadata:
  name: easyshop-secrets
  namespace: easyshop

type: Opaque

stringData:
  JWT_SECRET: "pYk7wAWzOA2XH8IRlg+iyXWUuN0fnLoS7au6ndrvRKk="
  NEXTAUTH_SECRET: "NsRgBK5YDR38kxGhqY/PhSNZYFghjSL1vlaAt16+EXg="
